export const EMOJI_MAP: Record<string, string> = {
  // Smileys & Emotion
  'grinning': '😀', 'smiley': '😃', 'smile': '😄', 'grin': '😁', 'laughing': '😆',
  'sweat_smile': '😅', 'rofl': '🤣', 'joy': '😂', 'slight_smile': '🙂', 'upside_down': '🙃',
  'wink': '😉', 'blush': '😊', 'innocent': '😇', 'heart_eyes': '😍', 'star_eyes': '🤩',
  'kissing_heart': '😘', 'kissing': '😗', 'yum': '😋', 'stuck_out_tongue': '😛',
  'stuck_out_tongue_wink_eye': '😜', 'zany_face': '🤪', 'stuck_out_tongue_closed_eyes': '😝',
  'money_mouth': '🤑', 'hugging': '🤗', 'shushing': '🤫', 'thinking': '🤔', 'zipper_mouth': '🤐',
  'neutral_face': '😐', 'expressionless': '😑', 'no_mouth': '😶', 'smirk': '😏', 'unamused': '😒',
  'roll_eyes': '🙄', 'grimacing': '😬', 'lying_face': '🤥', 'relieved': '😌', 'pensive': '😔',
  'sleepy': '😪', 'sleeping': '😴', 'mask': '😷', 'thermometer_face': '🤒', 'head_bandage': '🤕',
  'nauseated': '🤢', 'vomiting': '🤮', 'sneezing': '🤧', 'hot_face': '🥵', 'cold_face': '🥶',
  'woozy_face': '🥴', 'dizzy_face': '😵', 'exploding_head': '🤯', 'cowboy': '🤠',
  'partying_face': '🥳', 'sunglasses': '😎', 'nerd': '🤓', 'monocle': '🧐', 'confused': '😕',
  'worried': '😟', 'frowning': '🙁', 'open_mouth': '😮', 'hushed': '😯', 'astonished': '😲',
  'flushed': '😳', 'pleading': '🥺', 'frowning_face': '☹️', 'anguished': '😧', 'fearful': '😨',
  'cold_sweat': '😰', 'disappointed_relieved': '😥', 'cry': '😢', 'sob': '😭', 'scream': '😱',
  'confounded': '😖', 'persevere': '😣', 'disappointed': '😞', 'sweat': '😓', 'weary': '😩',
  'tired_face': '😫', 'yawn': '🥱', 'triumph': '😤', 'rage': '😡', 'angry': '😠',
  'cursing_face': '🤬', 'skull': '💀', 'skull_crossbones': '☠️', 'ghost': '👻', 'alien': '👽',
  'space_invader': '👾', 'robot': '🤖', 'poop': '💩',
  
  // Animals & Nature
  'monkey_face': '🐵', 'monkey': '🐒', 'gorilla': '🦍', 'dog': '🐶', 'dog2': '🐕',
  'poodle': '🐩', 'wolf': '🐺', 'fox_face': '🦊', 'raccoon': '🦝', 'cat': '🐱',
  'cat2': '🐈', 'lion': '🦁', 'tiger': '🐯', 'tiger2': '🐅', 'leopard': '🐆',
  'horse': '🐴', 'horse2': '🐎', 'unicorn': '🦄', 'zebra': '🦓', 'deer': '🦌',
  'cow': '🐮', 'ox': '🐂', 'cow2': '🐄', 'pig': '🐷', 'pig2': '🐖',
  'boar': '🐗', 'pig_nose': '🐽', 'ram': '🐏', 'sheep': '🐑', 'goat': '🐐',
  'camel': '🐪', 'camel2': '🐫', 'llama': '🦙', 'giraffe': '🦒', 'elephant': '🐘',
  'rhinoceros': '🦏', 'hippo': '🦛', 'mouse': '🐭', 'mouse2': '🐁', 'rat': '🐀',
  'hamster': '🐹', 'rabbit': '🐰', 'rabbit2': '🐇', 'chipmunk': '🐿', 'hedgehog': '🦔',
  'bat': '🦇', 'bear': '🐻', 'panda_face': '🐼', 'kangaroo': '🦘', 'badger': '🦡',
  'paw_prints': '🐾', 'turkey': '🦃', 'chicken': '🐔', 'rooster': '🐓', 'hatching_chick': '🐣',
  'baby_chick': '🐤', 'hatched_chick': '🐥', 'bird': '🐦', 'penguin': '🐧', 'dove': '🕊',
  'eagle': '🦅', 'duck': '🦆', 'swan': '🦢', 'owl': '🦉', 'flamingo': '🦩',
  'peacock': '🦚', 'parrot': '🦜', 'frog': '🐸', 'crocodile': '🐊', 'turtle': '🐢',
  'lizard': '🦎', 'snake': '🐍', 'dragon_face': '🐲', 'dragon': '🐉', 'whale': '🐳',
  'whale2': '🐋', 'dolphin': '🐬', 'fish': '🐟', 'tropical_fish': '🐠', 'blowfish': '🐡',
  'shark': '🦈', 'octopus': '🐙', 'shell': '🐚', 'snail': '🐌', 'butterfly': '🦋',
  'bug': '🐛', 'ant': '🐜', 'bee': '🐝', 'lady_beetle': '🐞', 'spider': '🕷',
  'bouquet': '💐', 'cherry_blossom': '🌸', 'rose': '🌹', 'hibiscus': '🌺', 'sunflower': '🌻',
  'blossom': '🌼', 'tulip': '🌷', 'seedling': '🌱', 'evergreen_tree': '🌲', 'palm_tree': '🌴',
  'cactus': '🌵', 'maple_leaf': '🍁', 'fallen_leaf': '🍂', 'mushroom': '🍄',
  
  // Food & Drink
  'grapes': '🍇', 'melon': '🍈', 'watermelon': '🍉', 'tangerine': '🍊', 'lemon': '🍋',
  'banana': '🍌', 'pineapple': '🍍', 'mango': '🥭', 'apple': '🍎', 'green_apple': '🍏',
  'pear': '🍐', 'peach': '🍑', 'cherries': '🍒', 'strawberry': '🍓', 'blueberry': '🫐',
  'kiwi': '🥝', 'tomato': '🍅', 'avocado': '🥑', 'eggplant': '🍆', 'potato': '🥔',
  'carrot': '🥕', 'corn': '🌽', 'hot_pepper': '🌶', 'cucumber': '🥒', 'broccoli': '🥦',
  'peanuts': '🥜', 'chestnut': '🌰', 'bread': '🍞', 'croissant': '🥐', 'cheese': '🧀',
  'meat_on_bone': '🍖', 'poultry_leg': '🍗', 'bacon': '🥓', 'hamburger': '🍔', 'fries': '🍟',
  'pizza': '🍕', 'hotdog': '🌭', 'sandwich': '🥪', 'taco': '🌮', 'burrito': '🌯',
  'cooking': '🍳', 'salad': '🥗', 'popcorn': '🍿', 'bento': '🍱', 'rice': '🍚',
  'curry': '🍛', 'ramen': '🍜', 'spaghetti': '🍝', 'sushi': '🍣', 'fried_shrimp': '🍤',
  'dango': '🍡', 'dumpling': '🥟', 'ice_cream': '🍦', 'shaved_ice': '🍧', 'doughnut': '🍩',
  'cookie': '🍪', 'birthday': '🎂', 'cake': '🍰', 'chocolate_bar': '🍫', 'candy': '🍬',
  'lollipop': '🍭', 'custard': '🍮', 'honey_pot': '🍯', 'baby_bottle': '🍼', 'glass_of_milk': '🥛',
  'coffee': '☕️', 'tea': '🍵', 'sake': '🍶', 'champagne': '🍾', 'wine_glass': '🍷',
  'cocktail': '🍸', 'beer': '🍺', 'beers': '🍻', 'clinking_glasses': '🥂', 'bubble_tea': '🧋',
  
  // Activity
  'soccer': '⚽️', 'basketball': '🏀', 'football': '🏈', 'baseball': '⚾️', 'tennis': '🎾',
  'volleyball': '🏐', 'rugby_football': '🏉', '8ball': '🎱', 'ping_pong': '🏓', 'badminton': '🏸',
  'ice_hockey': '🏒', 'golf': '⛳️', 'kite': '🪁', 'bow_and_arrow': '🏹', 'fishing': '🎣',
  'boxing_glove': '🥊', 'martial_arts_uniform': '🥋', 'skateboard': '🛹', 'roller_skate': '🛼',
  'ski': '🎿', 'snowboarder': '🏂', 'parachute': '🪂', 'weight_lifting': '🏋️', 'wrestling': '🤼',
  'yoga': '🧘', 'surfing': '🏄', 'swimming': '🏊', 'rowing': '🚣', 'climbing': '🧗',
  'biking': '🚴', 'trophy': '🏆', 'first_place': '🥇', 'second_place': '🥈', 'third_place': '🥉',
  'medal_sports': '🏅', 'ticket': '🎫', 'circus_tent': '🎪', 'performing_arts': '🎭',
  'art': '🎨', 'clapper': '🎬', 'microphone': '🎤', 'headphones': '🎧', 'musical_keyboard': '🎹',
  'drum': '🥁', 'guitar': '🎸', 'violin': '🎻', 'game_die': '🎲', 'dart': '🎯',
  'video_game': '🎮', 'slot_machine': '🎰', 'puzzle_piece': '🧩',
  
  // Travel & Places
  'car': '🚗', 'taxi': '🚕', 'bus': '🚌', 'racing_car': '🏎', 'police_car': '🚓',
  'ambulance': '🚑', 'fire_engine': '🚒', 'tractor': '🚜', 'motorcycle': '🏍', 'bike': '🚲',
  'fuelpump': '⛽️', 'rotating_light': '🚨', 'anchor': '⚓️', 'sailboat': '⛵️', 'speedboat': '🚤',
  'ship': '🚢', 'airplane': '✈️', 'rocket': '🚀', 'flying_saucer': '🛸', 'luggage': '🧳',
  'watch': '⌚️', 'alarm_clock': '⏰', 'sun_with_face': '🌞', 'full_moon_with_face': '🌝',
  'star': '⭐', 'ringed_planet': '🪐', 'cloud': '☁️', 'partly_sunny': '⛅',
  'thunder_cloud_and_rain': '⛈', 'comet': '☄️', 'milky_way': '🌌', 'shooting_star': '🌠',
  'cityscape': '🏙', 'night_with_stars': '🌃', 'bridge_at_night': '🌉', 'volcano': '🌋',
  'mount_fuji': '🗻', 'mountain': '⛰', 'camping': '🏕', 'beach_with_umbrella': '🏖',
  'desert_island': '🏝', 'stadium': '🏟', 'building_construction': '🏗', 'house': '🏠',
  'office': '🏢', 'hospital': '🏥', 'bank': '🏦', 'hotel': '🏨', 'school': '🏫',
  'factory': '🏭', 'japanese_castle': '🏯', 'european_castle': '🏰', 'wedding': '💒',
  'tokyo_tower': '🗼', 'statue_of_liberty': '🗽', 'church': '⛪️', 'shinto_shrine': '⛩',
  'tent': '⛺️', 'sunrise': '🌅', 'city_sunset': '🌇', 'ferris_wheel': '🎡', 'roller_coaster': '🎢',
  
  // Symbols
  'heart': '❤️', 'orange_heart': '🧡', 'yellow_heart': '💛', 'green_heart': '💚',
  'blue_heart': '💙', 'purple_heart': '💜', 'black_heart': '🖤', 'white_heart': '🤍',
  'brown_heart': '🤎', 'broken_heart': '💔', 'heart_exclamation': '❣️', 'two_hearts': '💕',
  'revolving_hearts': '💞', 'heartbeat': '💓', 'heartpulse': '💗', 'sparkling_heart': '💖',
  'cupid': '💘', 'peace_symbol': '☮️', 'latin_cross': '✝️', 'star_and_crescent': '☪️',
  'om': '🕉', 'yin_yang': '☯️', 'aries': '♈️', 'taurus': '♉️', 'gemini': '♊️',
  'cancer': '♋️', 'leo': '♌️', 'virgo': '♍️', 'libra': '♎️', 'scorpio': '♏️',
  'sagittarius': '♐️', 'capricorn': '♑️', 'aquarius': '♒️', 'pisces': '♓️', 'id': '🆔',
  'atom_symbol': '⚛️', 'zzz': '💤', 'atm': '🏧', 'wc': '🚾', 'wheelchair': '♿️',
  'parking': '🅿️', 'restroom': '🚻', 'cinema': '🎦', 'signal_strength': '📶',
  'information_source': 'ℹ️', 'ng': '🆖', 'ok': '🆗', 'up': '🆙', 'cool': '🆒',
  'new': '🆕', 'free': '🆓', 'zero': '0️⃣', 'one': '1️⃣', 'two': '2️⃣', 'three': '3️⃣',
  'four': '4️⃣', 'five': '5️⃣', 'six': '6️⃣', 'seven': '7️⃣', 'eight': '8️⃣', 'nine': '9️⃣',
  'keycap_ten': '🔟', '1234': '🔢', 'hash': '#️⃣', 'play_pause': '⏯', 'next_track': '⏭',
  'fast_forward': '⏩', 'rewind': '⏪', 'arrow_right': '➡️', 'arrow_left': '⬅️',
  'arrow_up': '⬆️', 'arrow_down': '⬇️', 'twisted_rightwards_arrows': '🔀', 'repeat': '🔁',
  'musical_note': '🎵', 'notes': '🎶', 'plus': '➕', 'minus': '➖', 'infinity': '♾',
  'heavy_dollar_sign': '💲', 'tm': '™️', 'copyright': '©️', 'registered': '®️', 'check': '✔️',
  'red_circle': '🔴', 'blue_circle': '🔵', 'black_circle': '⚫️', 'white_circle': '⚪️',
  'small_red_triangle': '🔺', 'large_orange_diamond': '🔶', 'red_square': '🟥',
  'blue_square': '🟦', 'black_large_square': '⬛️', 'white_large_square': '⬜️',
  'loud_sound': '🔊', 'bell': '🔔', 'speech_balloon': '💬', 'thought_balloon': '💭',
  'spades': '♠️', 'clubs': '♣️', 'hearts': '♥️', 'diamonds': '♦️',
  
  // Flags
  'jp': '🇯🇵', 'us': '🇺🇸', 'kr': '🇰🇷', 'cn': '🇨🇳', 'de': '🇩🇪', 'es': '🇪🇸',
  'fr': '🇫🇷', 'it': '🇮🇹', 'ru': '🇷🇺', 'gb': '🇬🇧', 'br': '🇧🇷', 'ca': '🇨🇦',
  'in': '🇮🇳', 'tw': '🇹🇼', 'hk': '🇭🇰', 'vn': '🇻🇳', 'th': '🇹🇭', 'au': '🇦🇺',
  'sg': '🇸🇬', 'nl': '🇳🇱', 'ch': '🇨🇭', 'se': '🇸🇪', 'pl': '🇵🇱', 'pt': '🇵🇹',
  'mx': '🇲🇽', 'za': '🇿🇦', 'ae': '🇦🇪', 'ua': '🇺🇦', 'il': '🇮🇱',
  'flag_white': '🏳️', 'flag_black': '🏴', 'checkered_flag': '🏁',
  'triangular_flag_on_post': '🚩', 'rainbow_flag': '🏳️‍🌈', 'pirate_flag': '🏴‍☠️',
  
  // Gestures & People
  'thumbsup': '👍', 'thumbsdown': '👎', 'clap': '👏', 'wave': '👋', 'ok_hand': '👌',
  'raised_hand': '✋', 'fist': '✊', 'punch': '👊', 'v': '✌️', 'crossed_fingers': '🤞',
  'love_you': '🤟', 'metal': '🤘', 'call_me': '🤙', 'point_left': '👈', 'point_right': '👉',
  'point_up': '☝️', 'point_down': '👇', 'pray': '🙏', 'handshake': '🤝', 'muscle': '💪',
  'eyes': '👀', 'brain': '🧠', 'fire': '🔥', 'sparkles': '✨', 'boom': '💥',
};
